import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author USER
 */
public class AplikasiPerhitungaDiskon extends javax.swing.JFrame {

    private double currentDiskonPercentage = 0.10; // Default 10% (sesuai item pertama JComboBox)

    // Definisikan 5 kode kupon dan diskon tambahan
    private final Map<String, Double> kuponDiskon = new HashMap<>() {{
        put("CIHUY10", 0.10); // Diskon tambahan 10%
        put("MALAS20", 0.20); // Diskon tambahan 20%
        put("YNTKTS30", 0.30);   // Diskon tambahan 30%
        put("ACIKIWIR5", 0.05);   // Diskon tambahan 5%
        put("ADUHAI15", 0.15);  // Diskon tambahan 15%
    }};
    
    private double getComboBoxDiskon() {
        String selectedItem = (String) jComboBoxDiskon.getSelectedItem();
        if (selectedItem != null && selectedItem.endsWith("%")) {
            try {
                // Parse string "XX%" menjadi nilai desimal (e.g., 0.10)
                double diskon = Double.parseDouble(selectedItem.replace("%", "")) / 100.0;
                return diskon;
            } catch (NumberFormatException e) {
                return 0.0;
            }
        }
        return 0.0;
    }
    
    public AplikasiPerhitungaDiskon() {
        initComponents();
        setTitle("APLIKASI PENGHITUNG DISKON");
        setupComponentListeners();
        
        jComboBoxDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "20%", "30%", "40%", "50%", "60%", "70%" }));
        // TAMBAHKAN BARIS INI:
        jComboBoxDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDiskonItemStateChanged(evt);
                }
        });
    }
    
    private void setupComponentListeners() {
        // Tambahkan ItemListener untuk JComboBox
        jComboBoxDiskon.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                jComboBoxDiskonItemStateChanged(evt);
            }
        });
        
        // Tambahkan ChangeListener untuk JSlider
        jSliderDiskon.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                jSliderDiskonStateChanged(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldInputHarga = new javax.swing.JTextField();
        jComboBoxDiskon = new javax.swing.JComboBox<>();
        jButtonHitung = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHargaAkhir = new javax.swing.JTextField();
        jTextFieldPenghematan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRiwayat = new javax.swing.JTextArea();
        jSliderDiskon = new javax.swing.JSlider();
        jButtonKeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldKodeKupon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI PERHITUNGAN DISKON");

        jLabel2.setText("MASUKKAN HARGA");

        jLabel3.setText("PILIH DISKON");

        jTextFieldInputHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInputHargaActionPerformed(evt);
            }
        });

        jComboBoxDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "20%", "30%", "40%", "50%", "60%", "70%" }));
        jComboBoxDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDiskonItemStateChanged(evt);
            }
        });

        jButtonHitung.setText("HITUNG");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jLabel4.setText("HARGA AKHIR");

        jLabel5.setText("ANDA HEMAT SEBESAR");

        jTextFieldHargaAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaAkhirActionPerformed(evt);
            }
        });

        jTextFieldPenghematan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPenghematanActionPerformed(evt);
            }
        });

        jTextAreaRiwayat.setColumns(20);
        jTextAreaRiwayat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRiwayat);

        jSliderDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderDiskonStateChanged(evt);
            }
        });

        jButtonKeluar.setText("KELUAR");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jLabel6.setText("MASUKKAN KODE KUPON");

        jTextFieldKodeKupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKodeKuponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonKeluar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldPenghematan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldHargaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldInputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldKodeKupon, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jSliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jButtonHitung)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKeluar)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldInputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKodeKupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addComponent(jButtonHitung)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHargaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPenghematan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldInputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInputHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInputHargaActionPerformed

    private void jTextFieldKodeKuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeKuponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKodeKuponActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // Logika perhitungan diskon
        try {
            // 1. Ambil Harga Awal
            String hargaText = jTextFieldInputHarga.getText();
            double hargaAwal = Double.parseDouble(hargaText);
            
            // 2. Ambil Diskon Dasar (sudah diatur oleh JComboBox atau JSlider)
            double diskonDasar = currentDiskonPercentage;
            
            // 3. Ambil Diskon Kupon Tambahan
            double diskonKuponTambahan = 0.0;
            String kodeKupon = jTextFieldKodeKupon.getText().toUpperCase();
            if (kuponDiskon.containsKey(kodeKupon)) {
                diskonKuponTambahan = kuponDiskon.get(kodeKupon);
            }
            
            // 4. Hitung Total Diskon
            // Diskon total = 1 - ((1 - Diskon Dasar) * (1 - Diskon Kupon Tambahan))
            // Ini adalah cara umum menghitung diskon berjenjang.
            double totalDiskonRate = 1.0 - ((1.0 - diskonDasar) * (1.0 - diskonKuponTambahan));
            
            // 5. Hitung Harga Akhir dan Penghematan
            double penghematan = hargaAwal * totalDiskonRate;
            double hargaAkhir = hargaAwal - penghematan;
            
            // 6. Tampilkan Hasil
            jTextFieldHargaAkhir.setText(String.format("Rp %,.2f", hargaAkhir));
            jTextFieldPenghematan.setText(String.format("Rp %,.2f", penghematan));
            
            // 7. Tambahkan ke Riwayat
            String riwayatEntry = String.format(
                "Harga: Rp %,.2f | Diskon: %.0f%% | Kupon: %.0f%% | Akhir: Rp %,.2f\n",
                hargaAwal, 
                diskonDasar * 100, 
                diskonKuponTambahan * 100,
                hargaAkhir
            );
            jTextAreaRiwayat.append(riwayatEntry);

        } catch (NumberFormatException e) {
            // Penanganan Eksepsi (jika input harga bukan angka)
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Mohon masukkan angka yang valid untuk Harga.", 
                "Kesalahan Input", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            jTextFieldInputHarga.requestFocus();
        }
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jTextFieldHargaAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaAkhirActionPerformed

    private void jTextFieldPenghematanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPenghematanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPenghematanActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jComboBoxDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDiskonItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            // Perbarui currentDiskonPercentage saat JComboBox dipilih
            currentDiskonPercentage = getComboBoxDiskon();
            
            // Reset JSlider ke nilai yang sesuai agar sinkron dengan JComboBox
            int sliderValue = (int) (currentDiskonPercentage * 100);
            jSliderDiskon.setValue(sliderValue);
        }
    }//GEN-LAST:event_jComboBoxDiskonItemStateChanged

    private void jSliderDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderDiskonStateChanged
        // Perbarui currentDiskonPercentage saat JSlider digeser
        currentDiskonPercentage = jSliderDiskon.getValue() / 100.0;
        
        String diskonString = jSliderDiskon.getValue() + "%";
        jComboBoxDiskon.setSelectedItem(diskonString);
    }//GEN-LAST:event_jSliderDiskonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitungaDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitungaDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitungaDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitungaDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitungaDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitungaDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitungaDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitungaDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitungaDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JComboBox<String> jComboBoxDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderDiskon;
    private javax.swing.JTextArea jTextAreaRiwayat;
    private javax.swing.JTextField jTextFieldHargaAkhir;
    private javax.swing.JTextField jTextFieldInputHarga;
    private javax.swing.JTextField jTextFieldKodeKupon;
    private javax.swing.JTextField jTextFieldPenghematan;
    // End of variables declaration//GEN-END:variables
}
